### ISSUE TITLE
はまりどころ

### ISSUE THREAD

**Issue by dai-motoki** [dai-motoki/niwatoko#8]
https://x.com/kk_design_dev/status/1787986324697624618

に下記を参照して実行していたところ
[https://niwatoko2.vercel.app/usage.html](https://t.co/W2Q5AvvbW6)

環境変数をexportせずに実行すると最初にclaudeではなく、OPENAI_API_KEYがないというエラーが出たため、openAIのkeyを設定していて少しできずにいました^^;
Translate post

**Comment by eieio81810** [comment]
ドハマりしてたのですがシンプルな解決方法でした。
https://github.com/dai-motoki/niwatoko/pull/34

**Comment by eieio81810** [comment]
@dai-motoki  https://github.com/dai-motoki/niwatoko/pull/34 のマージありがとうございます！クローズ判断お願いします

**Comment by dai-motoki** [comment]
ありがとうございます！クローズします！
